/**
 * Single source of truth for the user-facing clinical and safety copy this app
 * renders. Views import these constants instead of re-typing the sentences, so
 * the non-diagnostic boundary cannot quietly diverge between views — one screen
 * saying "Not diagnostic." while another softens the same claim.
 *
 * This wording is the visible half of a real contract: the report finalization
 * path rejects prohibited diagnostic claims and requires the safety disclaimers
 * to be present, so the copy below is deliberately descriptive and never a
 * conclusion. Editing a constant here changes every surface that shows it.
 */

/** The non-diagnostic claim's two sentences, kept apart for one-line usages. */
export const DECISION_SUPPORT_ONLY = "Decision-support only.";
export const NOT_DIAGNOSTIC_STATEMENT = "Not diagnostic.";

/** The claim that anchors almost every safety surface in the app. */
export const NON_DIAGNOSTIC_CLAIM = `${DECISION_SUPPORT_ONLY} ${NOT_DIAGNOSTIC_STATEMENT}`;

/** The short form used where the claim is rendered as a badge. */
export const NOT_DIAGNOSTIC_BADGE = "Not diagnostic";

/** The one default body shared by every safety-note component. */
export const SAFETY_NOTICE_DEFAULT = `${NON_DIAGNOSTIC_CLAIM} Therapist review required before clinical use.`;

/** The review obligation, in the clause and sentence forms views need. */
export const THERAPIST_REVIEW_REQUIRED_CLAUSE = "Therapist review required";
export const THERAPIST_REVIEW_REQUIRED = `${THERAPIST_REVIEW_REQUIRED_CLAUSE}.`;
export const THERAPIST_REVIEW_REMAINS_REQUIRED_CLAUSE = "Therapist review remains required";
export const THERAPIST_REVIEW_REMAINS_REQUIRED = `${THERAPIST_REVIEW_REMAINS_REQUIRED_CLAUSE}.`;
export const THERAPIST_REVIEW_AND_CONSENT_REQUIRED =
  "Therapist review and consent gates remain required.";
export const THERAPIST_SIGNOFF_CLAUSE = "Therapist review and sign-off remain required";
export const THERAPIST_REVIEW_SIGNOFF_REQUIRED = `${THERAPIST_SIGNOFF_CLAUSE}.`;

/** Where the obligation is shown as a short status label rather than a sentence. */
export const REVIEW_REQUIRED_LABEL = "Review required";
export const TRANSCRIPT_REVIEW_REQUIRED_LABEL = "Transcript review required";
export const DRAFT_TRANSCRIPT_READY_LABEL = "Draft transcript ready — review required";

/** Notes stating what the workflow itself does and does not allow. */
export const EXPORT_ELIGIBILITY_NOTE =
  "Reports remain export-eligible only after therapist review and sign-off. Stale drafts require regeneration.";
export const QA_INTERPRETATION_NOTE =
  "QA supports transcript review and requires therapist interpretation.";
export const DECISION_SUPPORT_ONLY_LABEL = "Decision-support only";

/** Interpretation wording attached to feature signals. */
export const THERAPIST_INTERPRETATION_REQUIRED = "Therapist interpretation required.";
export const THERAPIST_INTERPRETATION_IS_REQUIRED_CLAUSE = "Therapist interpretation is required";
export const INTERPRETATION_HINT =
  "Therapist-editable descriptive draft. Do not treat as a diagnosis or final conclusion.";

/** Draft-transcript labels, keyed to how the audio actually arrived. */
export const DRAFT_TRANSCRIPT_LABEL = "Draft transcript — therapist review required.";
export const DRAFT_ASR_TRANSCRIPT_LABEL = "Draft ASR transcript — therapist review required.";

/** Caution lines attached to numbers a reader could over-interpret. */
export const NON_DIAGNOSTIC_SCORE_CAUTION =
  "Research prototype scores — non-diagnostic. Therapist clinical judgment required.";
export const LONGITUDINAL_DELTA_CAUTION =
  "Descriptive numerical delta only; indeterminate clinical interpretation. Not a diagnostic tool.";
export const EXPERIMENTAL_ASR_CAUTION =
  "ASR transcription is experimental and not clinically validated. Therapist review required.";

/** The full limitation paragraph that accompanies generated report content. */
export const LIMITATION_TEXT =
  "This report is generated by a clinical decision-support prototype. It is not a diagnostic tool. All transcript, feature, AI-assisted summary, and report content must be reviewed and signed off by a qualified therapist or clinician.";

/**
 * Every canonical string above, as (name, value) pairs, so the single-sourcing
 * test enumerates the registry instead of restating the list. Adding a constant
 * here is what puts it under the re-inlining check.
 */
export const CLINICAL_SAFETY_COPY: ReadonlyArray<readonly [string, string]> = [
  ["DECISION_SUPPORT_ONLY", DECISION_SUPPORT_ONLY],
  ["NOT_DIAGNOSTIC_STATEMENT", NOT_DIAGNOSTIC_STATEMENT],
  ["NON_DIAGNOSTIC_CLAIM", NON_DIAGNOSTIC_CLAIM],
  ["NOT_DIAGNOSTIC_BADGE", NOT_DIAGNOSTIC_BADGE],
  ["SAFETY_NOTICE_DEFAULT", SAFETY_NOTICE_DEFAULT],
  ["THERAPIST_REVIEW_REQUIRED_CLAUSE", THERAPIST_REVIEW_REQUIRED_CLAUSE],
  ["THERAPIST_REVIEW_REQUIRED", THERAPIST_REVIEW_REQUIRED],
  ["THERAPIST_REVIEW_REMAINS_REQUIRED_CLAUSE", THERAPIST_REVIEW_REMAINS_REQUIRED_CLAUSE],
  ["THERAPIST_REVIEW_REMAINS_REQUIRED", THERAPIST_REVIEW_REMAINS_REQUIRED],
  ["THERAPIST_REVIEW_AND_CONSENT_REQUIRED", THERAPIST_REVIEW_AND_CONSENT_REQUIRED],
  ["THERAPIST_SIGNOFF_CLAUSE", THERAPIST_SIGNOFF_CLAUSE],
  ["THERAPIST_REVIEW_SIGNOFF_REQUIRED", THERAPIST_REVIEW_SIGNOFF_REQUIRED],
  ["REVIEW_REQUIRED_LABEL", REVIEW_REQUIRED_LABEL],
  ["TRANSCRIPT_REVIEW_REQUIRED_LABEL", TRANSCRIPT_REVIEW_REQUIRED_LABEL],
  ["DRAFT_TRANSCRIPT_READY_LABEL", DRAFT_TRANSCRIPT_READY_LABEL],
  ["EXPORT_ELIGIBILITY_NOTE", EXPORT_ELIGIBILITY_NOTE],
  ["QA_INTERPRETATION_NOTE", QA_INTERPRETATION_NOTE],
  ["DECISION_SUPPORT_ONLY_LABEL", DECISION_SUPPORT_ONLY_LABEL],
  ["THERAPIST_INTERPRETATION_REQUIRED", THERAPIST_INTERPRETATION_REQUIRED],
  ["THERAPIST_INTERPRETATION_IS_REQUIRED_CLAUSE", THERAPIST_INTERPRETATION_IS_REQUIRED_CLAUSE],
  ["INTERPRETATION_HINT", INTERPRETATION_HINT],
  ["DRAFT_TRANSCRIPT_LABEL", DRAFT_TRANSCRIPT_LABEL],
  ["DRAFT_ASR_TRANSCRIPT_LABEL", DRAFT_ASR_TRANSCRIPT_LABEL],
  ["NON_DIAGNOSTIC_SCORE_CAUTION", NON_DIAGNOSTIC_SCORE_CAUTION],
  ["LONGITUDINAL_DELTA_CAUTION", LONGITUDINAL_DELTA_CAUTION],
  ["EXPERIMENTAL_ASR_CAUTION", EXPERIMENTAL_ASR_CAUTION],
  ["LIMITATION_TEXT", LIMITATION_TEXT],
];
