import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { SafetyNotice } from "@/components/safety-notice";
import { SafetyNote } from "@/components/workbench-ui";
import * as safetyCopy from "@/lib/clinical-safety-copy";
import {
  CLINICAL_SAFETY_COPY,
  NON_DIAGNOSTIC_CLAIM,
  SAFETY_NOTICE_DEFAULT,
} from "@/lib/clinical-safety-copy";
import { createInitialWorkflowState } from "@/lib/workflow";
import { createDraftText } from "@/features/sessions/report/session-report-model";
import { extractFeaturesBlockedReason } from "@/lib/workflow-gates";
import { findEmbeddedLabels, findReinlinedLabels, findUnusedLabels } from "./support/single-sourcing";

// The registry module is where the constants legitimately appear as literals.
const SAFETY_COPY_MODULE = "src/lib/clinical-safety-copy.ts";
const EXCLUDE_SELF = { exclude: [SAFETY_COPY_MODULE] };

describe("clinical safety copy", () => {
  it("registers every exported safety string, so none escapes the scan", () => {
    // A constant added above the registry would be rendered by a view yet never
    // checked for re-inlining; comparing against the real exports keeps the two
    // in step instead of restating the list here.
    const exportedStrings = Object.entries(safetyCopy)
      .filter(([, value]) => typeof value === "string")
      .map(([name]) => name)
      .sort();

    expect(exportedStrings).toEqual(CLINICAL_SAFETY_COPY.map(([name]) => name).sort());
  });

  it("states the non-diagnostic boundary in one shared sentence", () => {
    expect(safetyCopy.DECISION_SUPPORT_ONLY).toBe("Decision-support only.");
    expect(safetyCopy.NOT_DIAGNOSTIC_STATEMENT).toBe("Not diagnostic.");
    expect(NON_DIAGNOSTIC_CLAIM).toBe("Decision-support only. Not diagnostic.");
    expect(SAFETY_NOTICE_DEFAULT).toBe(
      "Decision-support only. Not diagnostic. Therapist review required before clinical use.",
    );
  });

  it("pins the reviewed wording of every registered safety string", () => {
    // Single-sourcing keeps views consistent with the registry; this pin keeps
    // the registry itself from being reworded by accident, since any edit here
    // changes what every view tells a therapist.
    expect(Object.fromEntries(CLINICAL_SAFETY_COPY)).toEqual({
      DECISION_SUPPORT_ONLY: "Decision-support only.",
      NOT_DIAGNOSTIC_STATEMENT: "Not diagnostic.",
      NON_DIAGNOSTIC_CLAIM: "Decision-support only. Not diagnostic.",
      NOT_DIAGNOSTIC_BADGE: "Not diagnostic",
      SAFETY_NOTICE_DEFAULT:
        "Decision-support only. Not diagnostic. Therapist review required before clinical use.",
      THERAPIST_REVIEW_REQUIRED_CLAUSE: "Therapist review required",
      THERAPIST_REVIEW_REQUIRED: "Therapist review required.",
      THERAPIST_REVIEW_REMAINS_REQUIRED_CLAUSE: "Therapist review remains required",
      THERAPIST_REVIEW_REMAINS_REQUIRED: "Therapist review remains required.",
      THERAPIST_REVIEW_AND_CONSENT_REQUIRED:
        "Therapist review and consent gates remain required.",
      THERAPIST_SIGNOFF_CLAUSE: "Therapist review and sign-off remain required",
      THERAPIST_REVIEW_SIGNOFF_REQUIRED: "Therapist review and sign-off remain required.",
      REVIEW_REQUIRED_LABEL: "Review required",
      TRANSCRIPT_REVIEW_REQUIRED_LABEL: "Transcript review required",
      DRAFT_TRANSCRIPT_READY_LABEL: "Draft transcript ready — review required",
      EXPORT_ELIGIBILITY_NOTE:
        "Reports remain export-eligible only after therapist review and sign-off. Stale drafts require regeneration.",
      QA_INTERPRETATION_NOTE:
        "QA supports transcript review and requires therapist interpretation.",
      DECISION_SUPPORT_ONLY_LABEL: "Decision-support only",
      THERAPIST_INTERPRETATION_REQUIRED: "Therapist interpretation required.",
      THERAPIST_INTERPRETATION_IS_REQUIRED_CLAUSE: "Therapist interpretation is required",
      INTERPRETATION_HINT:
        "Therapist-editable descriptive draft. Do not treat as a diagnosis or final conclusion.",
      DRAFT_TRANSCRIPT_LABEL: "Draft transcript — therapist review required.",
      DRAFT_ASR_TRANSCRIPT_LABEL: "Draft ASR transcript — therapist review required.",
      NON_DIAGNOSTIC_SCORE_CAUTION:
        "Research prototype scores — non-diagnostic. Therapist clinical judgment required.",
      LONGITUDINAL_DELTA_CAUTION:
        "Descriptive numerical delta only; indeterminate clinical interpretation. Not a diagnostic tool.",
      EXPERIMENTAL_ASR_CAUTION:
        "ASR transcription is experimental and not clinically validated. Therapist review required.",
      LIMITATION_TEXT:
        "This report is generated by a clinical decision-support prototype. It is not a diagnostic tool. All transcript, feature, AI-assisted summary, and report content must be reviewed and signed off by a qualified therapist or clinician.",
    });
  });

  it("gives both safety-note components one canonical default body", () => {
    // Two components carrying their own default wording is how the same claim
    // drifts apart, so the defaults are compared by rendering, not by reading.
    const safetyNotice = render(<SafetyNotice />);
    expect(screen.getByText(SAFETY_NOTICE_DEFAULT)).toBeInTheDocument();
    safetyNotice.unmount();

    render(<SafetyNote />);
    expect(screen.getByText(SAFETY_NOTICE_DEFAULT)).toBeInTheDocument();
  });

  it("keeps every safety string single-sourced instead of re-inlined by a view", () => {
    // A re-inlined copy still renders the right words today, so only this check
    // catches it drifting away from the registry later.
    expect(findReinlinedLabels(CLINICAL_SAFETY_COPY, EXCLUDE_SELF)).toEqual([]);
  });

  it("forbids restating a safety claim inside a longer sentence", () => {
    // The stricter pass: a view may append its own clause to a canonical claim,
    // but the claim itself has to come from the registry rather than be retyped
    // as part of a new sentence.
    expect(findEmbeddedLabels(CLINICAL_SAFETY_COPY, EXCLUDE_SELF)).toEqual([]);
  });

  it("leaves no registered safety string unimported", () => {
    expect(findUnusedLabels(CLINICAL_SAFETY_COPY, EXCLUDE_SELF)).toEqual([]);
  });

  it("composes the sentences that append a clause to a claim without changing them", () => {
    // The views build their own sentence around a canonical claim. Splitting it
    // across a constant must leave the joined sentence exactly as it read when
    // the wording lived inline, so the joins are asserted where they are built.
    const state = { ...createInitialWorkflowState(), transcriptReady: true };
    expect(extractFeaturesBlockedReason(state)).toBe(
      "Feature extraction requires a saved, reviewed, and attested transcript.",
    );

    expect(createDraftText(state)).toContain(
      "Decision-support only.\nNot diagnostic.\nTherapist review required.",
    );
  });

  it("keeps the draft-transcript labels distinct from the claim they carry", () => {
    expect(safetyCopy.DRAFT_TRANSCRIPT_LABEL).toContain("therapist review required");
    expect(safetyCopy.DRAFT_ASR_TRANSCRIPT_LABEL).toContain("therapist review required");
    expect(safetyCopy.DRAFT_ASR_TRANSCRIPT_LABEL).not.toBe(safetyCopy.DRAFT_TRANSCRIPT_LABEL);
  });
});
