from __future__ import annotations

from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator


LIMITATION_TEXT = (
    "This report is generated by a clinical decision-support prototype. "
    "It does not diagnose ASD or any speech-language disorder. All transcript, "
    "feature, AI-assisted summary, and report content must be reviewed and "
    "signed off by a qualified therapist or clinician."
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class ReviewStatus(str, Enum):
    stale = "stale"
    draft = "Draft"
    needs_review = "Needs Review"
    attested = "Attested"
    processing = "Processing"
    failed = "Failed"
    ready = "Ready"
    signed_off = "Signed Off"
    withdrawn = "Withdrawn"


class QaStatus(str, Enum):
    not_run = "NOT_RUN"
    pass_ = "PASS"
    warning = "WARNING"
    fail = "FAIL"


class JobStatus(str, Enum):
    queued = "queued"
    processing = "processing"
    transcription_completed = "transcription_completed"
    needs_review = "needs_review"
    failed = "failed"
    cancelled = "cancelled"


class SpeakerCode(str, Enum):
    CHI = "CHI"
    THER = "THER"
    PAR = "PAR"
    INV = "INV"
    UNK = "UNK"


class ChildCaseBase(BaseModel):
    child_code: str
    organization_id: str = "pilot_org_001"
    care_team_user_ids: list[str] = Field(default_factory=list)
    primary_therapist_user_id: str | None = None
    nickname: str | None = None
    age_months: int = Field(ge=0, le=240)
    language: str = "English"
    consent_status: str = "pending"
    notes: str = ""

    @model_validator(mode="after")
    def ensure_primary_therapist_alignment(self):
        if self.primary_therapist_user_id and self.primary_therapist_user_id not in self.care_team_user_ids:
            self.care_team_user_ids = [*self.care_team_user_ids, self.primary_therapist_user_id]
        return self


class ChildCaseCreate(ChildCaseBase):
    child_code: str = Field(min_length=1, max_length=64)
    nickname: str | None = Field(default=None, max_length=120)
    language: str = Field(default="English", min_length=1, max_length=64)
    notes: str = Field(default="", max_length=2000)

    @field_validator("child_code", "language")
    @classmethod
    def strip_required_text(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("must not be blank")
        return value

    @field_validator("nickname", "notes")
    @classmethod
    def strip_optional_text(cls, value: str | None) -> str | None:
        return value.strip() if value is not None else None


class ChildCaseUpdate(BaseModel):
    nickname: str | None = None
    care_team_user_ids: list[str] | None = None
    primary_therapist_user_id: str | None = None
    age_months: int | None = Field(default=None, ge=0, le=240)
    language: str | None = None
    consent_status: str | None = None
    notes: str | None = None


class ChildCase(ChildCaseBase):
    case_id: str
    version: int = 1
    latest_session_date: str | None = None
    latest_session_status: ReviewStatus = ReviewStatus.draft
    latest_report_status: ReviewStatus = ReviewStatus.draft
    review_priority: str = "low"
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class OrganizationMembershipCreate(BaseModel):
    user_id: str
    display_name: str
    role: str
    active: bool = True


class OrganizationMembership(BaseModel):
    membership_id: str
    organization_id: str
    user_id: str
    display_name: str
    role: str
    active: bool = True
    created_at: datetime = Field(default_factory=utc_now)


class OrganizationInvitationCreate(BaseModel):
    email: str
    display_name: str
    role: str
    expires_at: datetime | None = None


class OrganizationInvitationAccept(BaseModel):
    user_id: str


class OrganizationInvitation(BaseModel):
    invitation_id: str
    organization_id: str
    email: str
    display_name: str
    role: str
    status: Literal["pending", "accepted", "expired", "revoked"] = "pending"
    invited_by: str
    accepted_user_id: str | None = None
    expires_at: datetime
    created_at: datetime = Field(default_factory=utc_now)
    accepted_at: datetime | None = None


class OrganizationReadinessItem(BaseModel):
    key: str
    label: str
    status: Literal["ready", "attention", "blocked"]
    detail: str
    evidence: list[str] = Field(default_factory=list)
    next_action: str = ""


class OrganizationReadiness(BaseModel):
    organization_id: str
    checked_by: str
    role: str
    environment: str
    pilot_ready: bool
    production_ready: bool
    active_memberships: int
    pending_invitations: int
    items: list[OrganizationReadinessItem]


class TenantIsolationSmokeCheck(BaseModel):
    key: str
    label: str
    passed: bool
    evidence: str


class TenantIsolationSmokeReport(BaseModel):
    status: Literal["passed", "failed"]
    checked_by: str
    organization_id: str
    checked_at: datetime = Field(default_factory=utc_now)
    checks: list[TenantIsolationSmokeCheck]


class CareTeamAssignmentCreate(BaseModel):
    user_id: str
    role: str = "therapist"
    active: bool = True
    is_primary: bool = False


class CareTeamAssignment(BaseModel):
    assignment_id: str
    organization_id: str
    case_id: str
    user_id: str
    role: str = "therapist"
    active: bool = True
    is_primary: bool = False
    created_at: datetime = Field(default_factory=utc_now)


class TherapySessionCreate(BaseModel):
    session_date: str
    session_type: str = "therapy_session"
    notes: str = ""


class TherapySessionUpdate(BaseModel):
    session_date: str | None = None
    session_type: str | None = None
    notes: str | None = None
    status: ReviewStatus | None = None
    cues_acknowledged_at: str | None = None
    cues_acknowledged_by: str | None = None


class TherapySession(BaseModel):
    session_id: str
    case_id: str
    organization_id: str = "pilot_org_001"
    version: int = 1
    session_date: str
    session_type: str
    notes: str = ""
    status: ReviewStatus = ReviewStatus.draft
    transcript_id: str | None = None
    feature_set_id: str | None = None
    ml_result_id: str | None = None
    ai_review_id: str | None = None
    report_id: str | None = None
    findings_stale: bool = False
    report_stale: bool = False
    cues_acknowledged_at: str | None = None
    cues_acknowledged_by: str | None = None
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TherapyGoalCreate(BaseModel):
    title: str
    target: str = ""
    status: str = "active"
    notes: str = ""


class TherapyGoalUpdate(BaseModel):
    title: str | None = None
    target: str | None = None
    status: str | None = None
    notes: str | None = None


class TherapyGoal(BaseModel):
    goal_id: str
    case_id: str
    organization_id: str = "pilot_org_001"
    title: str
    target: str = ""
    status: str = "active"
    notes: str = ""
    retained: bool = True
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class DependentTier(BaseModel):
    tier: str
    raw_text: str
    line_number: int
    supported: bool = False
    analyzed: bool = False
    parser_action: str = "preserved_not_analyzed"


class OrphanDependentTier(BaseModel):
    tier: str
    raw_text: str
    line_number: int
    parser_action: str = "preserved_unattached"


class Utterance(BaseModel):
    utterance_id: str
    speaker: SpeakerCode | str
    text: str
    start_ms: int | None = None
    end_ms: int | None = None
    unintelligible: bool = False
    notes: str = ""
    confidence: float | None = None
    dependent_tiers: list[DependentTier] = Field(default_factory=list)
    source: str = "manual"          # "manual" | "asr" | "mock" | "imported_chat"
    review_status: str = "draft"    # "draft" | "reviewed"



class Transcript(BaseModel):
    transcript_id: str
    session_id: str
    case_id: str
    organization_id: str = "pilot_org_001"
    source: str
    raw_text: str
    utterances: list[Utterance] = Field(default_factory=list)
    qa_status: QaStatus = QaStatus.not_run
    qa_issues: list["QaIssue"] = Field(default_factory=list)
    review_status: ReviewStatus = ReviewStatus.needs_review
    therapist_attested: bool = False
    attestation_reason: str = ""
    version: int = 1
    chat_metadata: dict = Field(default_factory=dict)
    orphan_dependent_tiers: list[OrphanDependentTier] = Field(default_factory=list)
    malformed_lines: list[dict] = Field(default_factory=list)
    parser_version: str = "chat-basic-v1"
    import_timestamp: datetime = Field(default_factory=utc_now)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TranscriptManualCreate(BaseModel):
    text: str
    language: str = "English"
    replace_existing: bool = False


class TranscriptUploadCha(BaseModel):
    filename: str
    cha_text: str
    replace_existing: bool = False


class TranscriptPatch(BaseModel):
    utterances: list[Utterance] | None = None
    raw_text: str | None = None
    reviewer_note: str = ""


class TranscriptReviewLine(BaseModel):
    line_id: str | None = None
    speaker: str
    text: str
    start_ms: int | None = None
    end_ms: int | None = None
    unclear: bool = False


class TranscriptReviewUpdate(BaseModel):
    base_version: int
    lines: list[TranscriptReviewLine]
    review_status: str | None = "IN_REVIEW"


class TranscriptSplitRequest(BaseModel):
    utterance_id: str
    split_at_character: int = Field(ge=1)


class TranscriptMergeRequest(BaseModel):
    first_utterance_id: str
    second_utterance_id: str


class TranscriptExport(BaseModel):
    transcript_id: str
    filename: str
    cha_text: str


class QaIssue(BaseModel):
    code: str
    severity: str  # "error" | "warning" | "info"
    message: str
    line_id: str | None = None
    field: str | None = None
    blocking: bool = False
    fix_suggestion: str | None = None
    source: str = "backend"
    validation_version: str = "chat-basic-v1"
    recommended_action: str | None = None


class QaReport(BaseModel):
    transcript_id: str
    overall_status: QaStatus
    issues: list[QaIssue] = Field(default_factory=list)
    can_extract_features: bool
    validation_version: str = "chat-basic-v1"


class AttestationRequest(BaseModel):
    attested_by: str = ""
    reason: str = "Therapist reviewed transcript quality."
    override_qa_failure: bool = False


class FeatureDefinition(BaseModel):
    feature_name: str
    display_name: str
    description: str
    value_type: str  # "integer" | "float" | "ratio" | "count" | "boolean"
    unit: str
    calculation_method: str
    required_inputs: list[str]
    numerator_definition: str | None = None
    denominator_definition: str | None = None
    default_thresholds: dict | None = None
    limitations: list[str]
    clinical_interpretation_caution: str
    feature_version: str = "features-basic-v1"
    provider_name: str = "BasicFeatureProvider"


class FeatureValue(BaseModel):
    name: str  # matches feature_name
    value: float | int | str | bool | None = None
    value_type: str = "count"
    unit: str = "count"
    numerator: float | int | None = None
    denominator: float | int | None = None
    thresholds_used: dict | None = None
    calculation_method: str | None = None
    provider_name: str = "BasicFeatureProvider"
    feature_version: str = "features-basic-v1"
    transcript_id: str | None = None
    session_id: str | None = None
    computed_at: datetime = Field(default_factory=utc_now)
    insufficient_data: bool = False
    warnings: list[str] = Field(default_factory=list)
    interpretation_hint: str = "Descriptive language sample value; therapist interpretation required."


class FeatureExtractionRequest(BaseModel):
    force_debug_override: bool = False
    override_reason: str = ""


class FeatureSet(BaseModel):
    feature_set_id: str
    organization_id: str = "pilot_org_001"
    session_id: str
    transcript_id: str
    transcript_version: int
    schema_version: str = "features-basic-v1"
    therapist_attested: bool
    extracted_at: datetime = Field(default_factory=utc_now)
    warnings: list[str] = Field(default_factory=list)
    features: list[FeatureValue]
    review_status: ReviewStatus = ReviewStatus.ready
    insufficient_data: bool = False
    provider_name: str = "BasicFeatureProvider"
    config_used: dict = Field(default_factory=dict)


class MLReviewRequest(BaseModel):
    provider_id: str | None = None
    force_regenerate: bool = False


class MLReadiness(BaseModel):
    ready: bool
    transcript_id: str
    session_id: str
    feature_result_id: str | None = None
    provider_id: str = "rule_based_review_cue"
    reason_codes: list[str] = Field(default_factory=list)
    reasons: list[str] = Field(default_factory=list)


class ReviewCueState(BaseModel):
    status: Literal["unreviewed", "acknowledged", "dismissed"] = "unreviewed"
    therapist_note: str = ""
    reviewed_by: str | None = None
    reviewed_by_name: str | None = None
    reviewed_at: datetime | None = None


class ReviewCue(BaseModel):
    cue_code: str
    severity: Literal["info", "review", "caution"]
    title: str
    explanation: str
    supporting_features: dict[str, float | int | str | bool | None] = Field(default_factory=dict)
    limitations: list[str] = Field(default_factory=list)
    recommended_next_review_step: str
    not_diagnostic: bool = True
    review_state: ReviewCueState = Field(default_factory=ReviewCueState)


EvidenceState = Literal[
    "available",
    "input_action_required",
    "unsupported_scope",
    "insufficient_reference_data",
    "system_unavailable",
]


class EvidenceAvailability(BaseModel):
    state: EvidenceState
    reason_code: str | None = None
    message: str
    workflow_can_continue: bool
    next_step: str | None = None


class AssociatedFeatureEvidence(BaseModel):
    feature_name: str
    observed_value: float | int | None
    position: Literal["below_iqr", "within_iqr", "above_iqr", "missing"]
    q1: float | None = None
    median: float | None = None
    q3: float | None = None
    caveat: str


class EvidenceReviewState(BaseModel):
    status: Literal["unreviewed", "reviewed", "disagreement"] = "unreviewed"
    therapist_note: str = ""
    reviewed_by: str | None = None
    reviewed_by_name: str | None = None
    reviewed_at: datetime | None = None


class ProfileEvidence(BaseModel):
    profile_code: Literal["TD", "DD", "ASD", "LT", "STI", "HL"]
    presentation_group: Literal["TD", "DD", "ASD", "OTHER"]
    status: Literal["comparable_patterns_observed", "limited_comparison", "not_available"]
    availability: EvidenceAvailability
    participant_count: int = Field(ge=0)
    corpus_count: int = Field(ge=0)
    associated_features: list[AssociatedFeatureEvidence] = Field(default_factory=list)
    review_state: EvidenceReviewState = Field(default_factory=EvidenceReviewState)


class PatternEvidence(BaseModel):
    status: Literal[
        "no_additional_pattern_cue",
        "additional_evidence_review_suggested",
        "not_available",
    ]
    availability: EvidenceAvailability
    associated_features: list[AssociatedFeatureEvidence] = Field(default_factory=list)
    review_state: EvidenceReviewState = Field(default_factory=EvidenceReviewState)


class EvidenceReviewPatch(BaseModel):
    status: Literal["reviewed", "disagreement"]
    therapist_note: str = ""

    @model_validator(mode="after")
    def require_disagreement_note(self):
        if self.status == "disagreement" and not self.therapist_note.strip():
            raise ValueError("A therapist note is required when recording disagreement.")
        return self


class MLResult(BaseModel):
    result_id: str
    organization_id: str = "pilot_org_001"
    transcript_id: str
    session_id: str
    feature_result_id: str
    provider_id: str
    provider_name: str
    provider_version: str
    model_id: str | None = None
    model_version: str | None = None
    input_feature_schema_version: str
    input_feature_hash: str
    generated_at: datetime = Field(default_factory=utc_now)
    status: Literal["completed", "unavailable", "insufficient_data", "failed"]
    cues: list[ReviewCue] = Field(default_factory=list)
    pattern_evidence: PatternEvidence | None = None
    profile_evidence: list[ProfileEvidence] = Field(default_factory=list)
    artifact_provenance: dict[str, str] = Field(default_factory=dict)
    scores: dict[str, float] | None = None
    confidence: str | None = None
    warnings: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    provider_config: dict = Field(default_factory=dict)
    not_diagnostic: bool = True
    decision_support_only: bool = True
    is_current: bool = True


class ReviewCuePatch(BaseModel):
    status: Literal["acknowledged", "dismissed"]
    therapist_note: str = ""


class AiAssistanceArea(BaseModel):
    area: str
    summary: str
    contributing_factors: list[str] = Field(default_factory=list)
    recommended_actions: list[str] = Field(default_factory=list)


class AiReview(BaseModel):
    ai_review_id: str
    organization_id: str = "pilot_org_001"
    session_id: str
    summary: str
    assistance_areas: list[AiAssistanceArea] = Field(default_factory=list)
    key_findings: list[str]
    concerns: list[str]
    strengths: list[str]
    limitations: list[str]
    recommended_review_actions: list[str]
    confidence_level: str
    requires_therapist_review: bool = True
    review_priority: str = "low"
    model_name: str = "local-rule-based-assistant"
    model_version: str = "v2-mock"
    prompt_version: str = "v2-safety-001"
    input_transcript_version: int
    feature_set_id: str | None = None
    feature_schema_version: str | None = None
    therapist_review_status: ReviewStatus = ReviewStatus.needs_review
    therapist_notes: str = ""
    rejected_reason: str = ""
    created_at: datetime = Field(default_factory=utc_now)


class AiReviewPatch(BaseModel):
    summary: str | None = None
    key_findings: list[str] | None = None
    concerns: list[str] | None = None
    strengths: list[str] | None = None
    limitations: list[str] | None = None
    recommended_review_actions: list[str] | None = None
    therapist_review_status: ReviewStatus | None = None
    therapist_notes: str | None = None
    rejected_reason: str | None = None


class AudioUploadRequest(BaseModel):
    filename: str
    content_type: str
    size_bytes: int
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None


class AudioFileMetadata(BaseModel):
    audio_file_id: str
    organization_id: str = "pilot_org_001"
    session_id: str
    case_id: str
    original_filename: str
    content_type: str
    size_bytes: int
    storage_mode: str = "metadata_only"
    object_key: str | None = None
    upload_status: str = "pending"
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None
    checksum_sha256: str | None = None
    uploaded_at: datetime | None = None
    storage_delete_status: str | None = None
    retained: bool = True
    created_at: datetime = Field(default_factory=utc_now)


class SignedUploadIntent(BaseModel):
    audio_file_id: str
    upload_url: str
    expires_in_seconds: int = 900
    storage_mode: str = "metadata_only"
    required_headers: dict[str, str] = Field(default_factory=dict)


class AudioUploadCompleteRequest(BaseModel):
    checksum_sha256: str | None = None
    size_bytes: int | None = None


class AudioProcessRequest(BaseModel):
    provider: str = "manual"
    draft_text: str = ""
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None


class TranscriptionJobConfig(BaseModel):
    """Provider-level configuration for a transcription job."""
    language: str = "en"
    return_word_timestamps: bool = True
    return_speaker_segments: bool = False
    allow_fallback_to_mock: bool = False


class TranscriptionJobRequest(BaseModel):
    """POST /sessions/{id}/audio/process body for the current audio pipeline."""
    audio_id: str | None = None
    provider: str = "mock"
    config: TranscriptionJobConfig = Field(default_factory=TranscriptionJobConfig)
    draft_text: str = ""   # backward compat with manual/paste flow



class AudioQualityReport(BaseModel):
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None
    status: str
    warnings: list[str] = Field(default_factory=list)


class AsrDraftResult(BaseModel):
    provider: str
    transcript_id: str | None = None
    utterance_count: int = 0
    speaker_assignment: str = "requires_therapist_correction"
    confidence_available: bool = False
    timestamps_available: bool = False
    diarization_available: bool = False
    warnings: list[str] = Field(default_factory=list)
    quality: AudioQualityReport


class ProcessingJob(BaseModel):
    job_id: str
    organization_id: str = "pilot_org_001"
    session_id: str
    status: JobStatus
    message: str
    error_code: str | None = None
    details: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class ReportSection(BaseModel):
    section_id: str
    title: str
    content: str
    not_diagnostic: bool = True
    decision_support_only: bool = True


class ReportProviderAvailability(BaseModel):
    provider_id: str
    available: bool
    reason: str | None = None
    requires_external_service: bool = False
    base_url: str | None = None
    model_name: str | None = None
    provider_version: str | None = None


class ReportProviderResult(BaseModel):
    status: Literal["completed", "unavailable", "failed"]
    sections: list[ReportSection]
    provider_id: str
    provider_name: str
    provider_version: str
    warnings: list[str] = Field(default_factory=list)
    raw_output_ref: str | None = None
    error_message: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ReportSafetyIssue(BaseModel):
    issue_id: str
    code: str
    severity: Literal["warning", "error"]
    message: str
    section_id: str | None = None
    detected_text: str | None = None
    normalized_detected_text: str | None = None
    start_offset: int | None = None
    end_offset: int | None = None
    suggested_fix: str | None = None
    suggested_replacement: str | None = None
    blocking: bool = True
    source: Literal["generation", "edit", "finalization"]
    rule_id: str | None = None


class ReportSafetyResult(BaseModel):
    status: Literal["passed", "warning", "failed"]
    validator_version: str = "safety-validator-v1.0"
    rule_set_version: str = "rules-v1.0"
    checked_at: datetime = Field(default_factory=utc_now)
    issues: list[ReportSafetyIssue] = Field(default_factory=list)
    required_disclaimers_present: bool = False
    missing_required_disclaimers: list[str] = Field(default_factory=list)
    prohibited_claims_found: bool = False
    prohibited_phrases_found: list[str] = Field(default_factory=list)
    checked_sections: list[str] = Field(default_factory=list)
    action_required: str | None = None
    finalization_blocked: bool = False


class ReportDraftRequest(BaseModel):
    report_type: str = "Session Review Report"
    replace_existing: bool = False


class ReportGenerationInput(BaseModel):
    transcript_id: str
    report_type: str = "Session Review Report"
    feature_result_id: str | None = None
    ml_result_id: str | None = None
    ml_skipped_reason: str | None = None
    validation_summary: str | None = None
    feature_schema_version: str | None = None
    therapist_notes: str | None = None
    session_goals: list[str] = Field(default_factory=list)
    generated_from_versions: dict[str, str] = Field(default_factory=dict)
    case_code: str
    session_date: str
    consent_status: str
    transcript_source: str
    qa_status: str
    therapist_attested: bool
    features: list[FeatureValue] = Field(default_factory=list)
    therapy_goals: list[TherapyGoal] = Field(default_factory=list)
    ai_review: AiReview | None = None
    previous_features: list[FeatureValue] = Field(default_factory=list)
    # Typical-development reference band ({age_band, task_type, features:
    # {runtime_feature: {q1, median, q3}}}) for the Progress Comparison section.
    reference_band: dict | None = None


class ReportGenerationRequest(BaseModel):
    report_type: str = "Session Review Report"
    provider_id: str = "template"
    allow_fallback_to_template: bool = False
    replace_existing: bool = False
    provider_config: dict[str, Any] = Field(default_factory=dict)
    therapist_notes: str | None = None
    session_goals: list[str] = Field(default_factory=list)
    ml_skipped_reason: str | None = None
    include_caregiver_summary: bool = True
    include_therapy_focus_suggestions: bool = True


class ReportFinalizeRequest(BaseModel):
    therapist_name: str | None = None
    confirmation_checked: bool = False
    final_notes: str | None = None
    signed_by: str | None = None
    attestation: str | None = None

    @model_validator(mode="before")
    @classmethod
    def handle_legacy_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "signed_by" in data and not data.get("therapist_name"):
                data["therapist_name"] = data["signed_by"]
            if "signed_by" in data and "confirmation_checked" not in data:
                data["confirmation_checked"] = True
        return data

    @model_validator(mode="after")
    def validate_name(self) -> ReportFinalizeRequest:
        if not self.therapist_name:
            self.therapist_name = self.signed_by
        return self


class ReportPatch(BaseModel):
    title: str | None = None
    markdown: str | None = None
    therapist_notes: str | None = None


class Report(BaseModel):
    report_id: str
    session_id: str
    case_id: str
    organization_id: str = "pilot_org_001"
    report_type: str
    title: str
    markdown: str
    html: str
    status: ReviewStatus = ReviewStatus.draft
    therapist_signoff_status: ReviewStatus = ReviewStatus.needs_review
    limitation_text: str = LIMITATION_TEXT
    export_timestamp: datetime | None = None
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    # Added v1.0 pilot-ready metadata
    requested_provider: str = "template"
    actual_provider: str = "template"
    provider_version: str = "1.0.0"
    fallback_reason: str | None = None
    rewrite_attempted: bool = False
    rewrite_succeeded: bool = False
    safety_validation_result: ReportSafetyResult | None = None
    finalized_safety_result: ReportSafetyResult | None = None
    finalization_blocked: bool = False
    validator_version: str = "safety-validator-v1.0"
    rule_set_version: str = "rules-v1.0"
    input_hash: str | None = None
    version: int = 1
    signed_by: str | None = None
    signed_at: datetime | None = None
    signed_snapshot_version: int | None = None
    signed_snapshot_hash: str | None = None
    signed_snapshot: dict[str, Any] | None = None
    supersedes_report_id: str | None = None
    revision_number: int = 1
    ai_drafting_requested: bool = False
    ai_drafting_enabled: bool = False
    ai_drafting_provider: str | None = None
    ai_drafting_model: str | None = None
    ai_drafting_region: str | None = None
    ai_drafting_input_hash: str | None = None

    # Trace inputs for audit and reproducibility
    transcript_id: str | None = None
    feature_result_id: str | None = None
    ml_result_id: str | None = None
    ml_skipped_reason: str | None = None
    validation_summary: str | None = None
    feature_schema_version: str | None = None
    therapist_notes: str | None = None
    session_goals: list[str] = Field(default_factory=list)
    generated_from_versions: dict[str, str] = Field(default_factory=dict)
    sections: list[ReportSection] = Field(default_factory=list)


class SignOffRequest(BaseModel):
    signed_by: str = "Demo Therapist"
    attestation: str = "I reviewed and accept responsibility for this report."


class ConsentWithdrawalRequest(BaseModel):
    reason: str
    redact_notes: bool = True


class ConsentWithdrawalResult(BaseModel):
    case_id: str
    status: ReviewStatus = ReviewStatus.withdrawn
    affected_records: dict[str, int]
    audit_message: str


PrivacyOperationType = Literal["case_export", "consent_withdrawal", "deletion_review"]
PrivacyOperationStatus = Literal["requested", "in_review", "completed", "rejected"]


class PrivacyOperationCreate(BaseModel):
    operation_type: PrivacyOperationType
    reason: str
    retention_days: int = Field(default=90, ge=0, le=3650)
    legal_hold: bool = False


class PrivacyOperationPatch(BaseModel):
    status: PrivacyOperationStatus | None = None
    admin_note: str | None = None
    legal_hold: bool | None = None


class PrivacyOperation(BaseModel):
    privacy_operation_id: str
    organization_id: str = "pilot_org_001"
    case_id: str
    operation_type: PrivacyOperationType
    status: PrivacyOperationStatus = "requested"
    requested_by: str
    requester_role: str = "therapist"
    reason: str
    admin_note: str = ""
    retention_days: int = 90
    legal_hold: bool = False
    deletion_review_required: bool = False
    preserve_evidence: bool = True
    eligible_for_deletion_at: datetime | None = None
    completed_at: datetime | None = None
    evidence_retained: dict[str, int] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    @model_validator(mode="after")
    def set_privacy_operation_defaults(self) -> PrivacyOperation:
        if self.operation_type == "deletion_review":
            self.deletion_review_required = True
            if self.eligible_for_deletion_at is None:
                self.eligible_for_deletion_at = self.created_at + timedelta(days=self.retention_days)
        return self


class PrivacyOperationAdminView(BaseModel):
    privacy_operation_id: str
    organization_id: str = "pilot_org_001"
    case_id: str
    operation_type: PrivacyOperationType
    status: PrivacyOperationStatus = "requested"
    requester_role: str = "therapist"
    retention_days: int = 90
    legal_hold: bool = False
    deletion_review_required: bool = False
    preserve_evidence: bool = True
    eligible_for_deletion_at: datetime | None = None
    completed_at: datetime | None = None
    evidence_retained: dict[str, int] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TimelineEvent(BaseModel):
    event_id: str
    label: str
    status: ReviewStatus
    occurred_at: datetime
    target_id: str


class ExportResponse(BaseModel):
    report_id: str
    format: str
    content: str
    content_type: str = "text/markdown"
    filename: str | None = None
    encoding: str = "utf-8"
    unavailable_reason: str | None = None
    limitation_text: str = LIMITATION_TEXT
    report_hash: str | None = None
    report_version: int | None = None
    signed_by: str | None = None
    export_timestamp: datetime | None = None


class AuditLogEntry(BaseModel):
    audit_id: str
    actor_id: str = "system"
    organization_id: str | None = None
    action: str
    target_id: str
    outcome: str = "success"
    correlation_id: str = "local"
    message: str
    timestamp: str


class AsrEvaluationInput(BaseModel):
    reference_text: str
    hypothesis_text: str
    reference_speakers: list[str] = Field(default_factory=list)
    hypothesis_speakers: list[str] = Field(default_factory=list)
    audio_duration_seconds: float = 0
    transcribed_duration_seconds: float = 0


class AsrDatasetEvaluationRequest(BaseModel):
    dataset_dir: str = "data/evaluation"
    hypothesis_dir: str | None = None
    output_dir: str | None = None


class AsrEvaluationReport(BaseModel):
    coverage: float
    utterance_count_error: int
    speaker_accuracy: float
    normalized_wer: float
    character_error_rate: float
    feature_deviation: dict[str, float]
    markdown: str
    json_report: dict[str, Any]


class AsrDatasetSampleResult(BaseModel):
    sample_id: str
    gold_transcript_path: str
    hypothesis_transcript_path: str | None = None
    audio_present: bool = False
    report: AsrEvaluationReport
    warnings: list[str] = Field(default_factory=list)


class AsrDatasetEvaluationResult(BaseModel):
    dataset_dir: str
    sample_count: int
    samples: list[AsrDatasetSampleResult]
    aggregate_metrics: dict[str, float]
    warnings: list[str] = Field(default_factory=list)
    report_paths: dict[str, str] = Field(default_factory=dict)


class ModelCardResult(BaseModel):
    path: str
    dataset_size: int
    feature_list: list[str]
    limitations: list[str]
    class_distribution: dict[str, int] = Field(default_factory=dict)
    metrics: dict[str, Any] = Field(default_factory=dict)


class DatasetBuildRequest(BaseModel):
    source_dir: str = "data/demo"
    include_unlabeled: bool = True


class FeatureTableRow(BaseModel):
    source_path: str
    label: str | None = None
    age_months: int | None = None
    sex: str | None = None
    language: str | None = None
    missing_metadata: list[str] = Field(default_factory=list)
    features: dict[str, float | int]


class DatasetBuildResult(BaseModel):
    rows: list[FeatureTableRow]
    dataset_size: int
    class_distribution: dict[str, int]
    warnings: list[str] = Field(default_factory=list)


class BaselineEvaluationRequest(BaseModel):
    source_dir: str = "data/demo"


class BaselineEvaluationResult(BaseModel):
    dataset_size: int
    class_distribution: dict[str, int]
    models: dict[str, dict[str, Any]]
    warnings: list[str] = Field(default_factory=list)


Transcript.model_rebuild()
