#!/usr/bin/env bash
# ==============================================================================
# LinguaLens Pilot Launch Orchestrator
# Automates preflight checks, backend API, Next.js frontend, and health probing.
# ==============================================================================

set -eo pipefail

# ANSI color styling
readonly BOLD='\033[1m'
readonly BLUE='\033[0;34m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly RED='\033[0;31m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m'

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/apps/api"
FRONTEND_DIR="$ROOT_DIR/apps/lingualens-app"
LOG_DIR="$ROOT_DIR/.local/logs"
mkdir -p "$LOG_DIR"

BACKEND_LOG="$LOG_DIR/backend.log"
FRONTEND_LOG="$LOG_DIR/frontend.log"

CHECK_ONLY=false
if [[ "${1:-}" == "--check-only" ]]; then
  CHECK_ONLY=true
fi

echo -e "${CYAN}${BOLD}"
echo "  _     _                          _                     "
echo " | |   (_)_ __   __ _ _   _  __ _| |    ___ _ __  ___   "
echo " | |   | | '_ \ / _\` | | | |/ _\` | |   / _ \ '_ \/ __|  "
echo " | |___| | | | | (_| | |_| | (_| | |__|  __/ | | \__ \  "
echo " |_____|_|_| |_|\__, |\__,_|\__,_|_____\___|_| |_|___/  "
echo "                |___/  Clinical Pilot Launcher v1.6.3   "
echo -e "${NC}"

echo -e "${BLUE}▶ [1/4] Running Pilot Pre-flight Verification...${NC}"

# Check Python version
if ! command -v python3 &>/dev/null; then
  echo -e "${RED}✗ Error: python3 is not installed or not on PATH.${NC}" >&2
  exit 1
fi

PYTHON_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo -e "  • Python runtime: ${GREEN}v$PYTHON_VER${NC}"

# Check Node version
if ! command -v node &>/dev/null; then
  echo -e "${RED}✗ Error: Node.js is not installed or not on PATH.${NC}" >&2
  exit 1
fi

NODE_VER=$(node -v)
echo -e "  • Node.js runtime: ${GREEN}$NODE_VER${NC}"

# Check port availability
check_port() {
  local port=$1
  if lsof -Pi :"$port" -sTCP:LISTEN -t >/dev/null 2>&1; then
    return 1
  fi
  return 0
}

if ! check_port 8000; then
  echo -e "  ${YELLOW}⚠ Warning: Port 8000 is already in use.${NC}"
fi

if ! check_port 3000; then
  echo -e "  ${YELLOW}⚠ Warning: Port 3000 is already in use.${NC}"
fi

# Ensure frontend .env.local exists
ENV_LOCAL="$FRONTEND_DIR/.env.local"
if [[ ! -f "$ENV_LOCAL" ]]; then
  cat <<EOT > "$ENV_LOCAL"
# Auto-generated by launch_pilot.sh
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8000/api/v1
EOT
  echo -e "  • Created: ${GREEN}$ENV_LOCAL${NC}"
fi

echo -e "${GREEN}✓ Preflight checks passed successfully.${NC}\n"

if [[ "$CHECK_ONLY" == "true" ]]; then
  echo -e "${GREEN}Preflight check mode completed (--check-only). Ready for launch.${NC}"
  exit 0
fi

# Trap cleanup handlers
BACKEND_PID=""
FRONTEND_PID=""

cleanup() {
  echo -e "\n${YELLOW}▶ Terminating pilot services gracefully...${NC}"
  if [[ -n "$BACKEND_PID" ]] && kill -0 "$BACKEND_PID" 2>/dev/null; then
    kill "$BACKEND_PID" 2>/dev/null || true
    echo -e "  • Stopped Backend API (PID: $BACKEND_PID)"
  fi
  if [[ -n "$FRONTEND_PID" ]] && kill -0 "$FRONTEND_PID" 2>/dev/null; then
    kill "$FRONTEND_PID" 2>/dev/null || true
    echo -e "  • Stopped Frontend Dev Server (PID: $FRONTEND_PID)"
  fi
  echo -e "${GREEN}✓ LinguaLens pilot shutdown complete.${NC}"
}
trap cleanup EXIT INT TERM

# Start Backend API
echo -e "${BLUE}▶ [2/4] Starting FastAPI Backend on port 8000...${NC}"
(
  cd "$BACKEND_DIR"
  export PYTHONPATH=".:$ROOT_DIR:$ROOT_DIR/src"
  uvicorn app.main:app --host 127.0.0.1 --port 8000 --log-level warning
) > "$BACKEND_LOG" 2>&1 &
BACKEND_PID=$!

# Wait for backend health
echo -n "  • Waiting for backend readiness..."
for _ in {1..30}; do
  if curl -s "http://127.0.0.1:8000/docs" >/dev/null 2>&1; then
    echo -e " ${GREEN}READY${NC} (PID: $BACKEND_PID)"
    break
  fi
  sleep 0.5
done

# Start Frontend
echo -e "${BLUE}▶ [3/4] Starting Next.js Clinician Workbench on port 3000...${NC}"
(
  cd "$FRONTEND_DIR"
  npm run dev -- -p 3000
) > "$FRONTEND_LOG" 2>&1 &
FRONTEND_PID=$!

echo -n "  • Waiting for frontend readiness..."
for _ in {1..40}; do
  if curl -s "http://localhost:3000" >/dev/null 2>&1; then
    echo -e " ${GREEN}READY${NC} (PID: $FRONTEND_PID)"
    break
  fi
  sleep 0.5
done

echo -e "\n${GREEN}${BOLD}======================================================================${NC}"
echo -e "${GREEN}${BOLD}  🚀 LINGUALENS CLINICAL PILOT ENVIRONMENT ACTIVE                     ${NC}"
echo -e "${GREEN}${BOLD}======================================================================${NC}"
echo -e "  • Therapist Workbench:      ${CYAN}${BOLD}http://localhost:3000${NC}"
echo -e "  • Clinician AI Assistant:   ${CYAN}${BOLD}http://localhost:3000/assistant${NC}"
echo -e "  • Backend API Swagger Docs: ${CYAN}${BOLD}http://127.0.0.1:8000/docs${NC}"
echo -e "  • Real-time Backend Logs:   ${BOLD}$BACKEND_LOG${NC}"
echo -e "  • Real-time Frontend Logs:  ${BOLD}$FRONTEND_LOG${NC}"
echo -e "${GREEN}${BOLD}======================================================================${NC}"
echo -e "Press ${BOLD}[Ctrl+C]${NC} at any time to halt all pilot processes.\n"

# Keep script running and wait on children
wait "$BACKEND_PID" "$FRONTEND_PID"
